export const artisticThemes = {
	arctic_frost: {
		name: "Arctic Frost",
		description: "Pale blues and crisp whites for a frozen landscape look",
		bg: "#F0F9FF",
		text: "#0C4A6E",
		water: "#BAE6FD",
		parks: "#E0F2FE",
		road_motorway: "#0EA5E9",
		road_primary: "#38BDF8",
		road_secondary: "#7DD3FC",
		road_tertiary: "#BAE6FD",
		road_residential: "#E0F2FE",
		road_default: "#7DD3FC"
	},
	aurora_glow: {
		name: "Aurora Glow",
		description: "Iridescent greens and pinks inspired by northern lights",
		bg: "#071428",
		text: "#E6FFF7",
		water: "#0EA5A5",
		parks: "#9EEAD6",
		road_motorway: "#7CF9D2",
		road_primary: "#5EEAD4",
		road_secondary: "#3BD6B6",
		road_tertiary: "#2FAF95",
		road_residential: "#1F7F6A",
		road_default: "#3BD6B6"
	},
	autumn_whisper: {
		name: "Autumn Whisper",
		description: "Burned oranges and deep ochre tints of fallen leaves",
		bg: "#451A03",
		text: "#FEF3C7",
		water: "#78350F",
		parks: "#92400E",
		road_motorway: "#F59E0B",
		road_primary: "#FBBF24",
		road_secondary: "#FCD34D",
		road_tertiary: "#FDE68A",
		road_residential: "#FEF3C7",
		road_default: "#FBBF24"
	},
	cyber_glitch: {
		name: "Cyber Glitch",
		description: "Electric purples and neon yellows for a digital future",
		bg: "#2E1065",
		text: "#F0ABFC",
		water: "#4C1D95",
		parks: "#581C87",
		road_motorway: "#FACC15",
		road_primary: "#EAB308",
		road_secondary: "#A855F7",
		road_tertiary: "#C084FC",
		road_residential: "#D8B4FE",
		road_default: "#A855F7"
	},
	deep_ocean: {
		name: "Deep Ocean",
		description: "Dark navy depths and teal currents",
		bg: "#082F49",
		text: "#E0F2FE",
		water: "#0C4A6E",
		parks: "#075985",
		road_motorway: "#0EA5E9",
		road_primary: "#38BDF8",
		road_secondary: "#7DD3FC",
		road_tertiary: "#BAE6FD",
		road_residential: "#0C4A6E",
		road_default: "#38BDF8"
	},
	dark_gold: {
		name: "Dark Gold",
		description: "Mewah — latar gelap dengan aksen emas hangat",
		bg: "#0B0A09",
		text: "#F6E7C1",
		water: "#061022",
		parks: "#26221A",
		road_motorway: "#D4AF37",
		road_primary: "#E6C07A",
		road_secondary: "#A3752B",
		road_tertiary: "#8B5E3C",
		road_residential: "#2F2B23",
		road_default: "#A3752B"
	},
	emerald_valley: {
		name: "Emerald Valley",
		description: "Lush mossy greens and deep forest tones",
		bg: "#022C22",
		text: "#D1FAE5",
		water: "#064E3B",
		parks: "#065F46",
		road_motorway: "#10B981",
		road_primary: "#34D399",
		road_secondary: "#059669",
		road_tertiary: "#047857",
		road_residential: "#064E3B",
		road_default: "#059669"
	},
	golden_era: {
		name: "Golden Era",
		description: "Rich yellows and deep browns recalling classic cartography",
		bg: "#FEFCE8",
		text: "#713F12",
		water: "#FEF08A",
		parks: "#FDE047",
		road_motorway: "#854D0E",
		road_primary: "#A16207",
		road_secondary: "#CA8A04",
		road_tertiary: "#EAB308",
		road_residential: "#FACC15",
		road_default: "#CA8A04"
	},
	lavender_mist: {
		name: "Lavender Mist",
		description: "Soft purples and muted greys - dreamy cartography",
		bg: "#F5F3FF",
		text: "#4C1D95",
		water: "#EDE9FE",
		parks: "#DDD6FE",
		road_motorway: "#5B21B6",
		road_primary: "#6D28D9",
		road_secondary: "#7C3AED",
		road_tertiary: "#8B5CF6",
		road_residential: "#A78BFA",
		road_default: "#7C3AED"
	},
	midnight_neon: {
		name: "Midnight Neon",
		description: "Black ink nights with neon accents for dramatic contrast",
		bg: "#030014",
		text: "#EAF7FF",
		water: "#062A66",
		parks: "#1B2B3B",
		road_motorway: "#00F5A0",
		road_primary: "#00E5FF",
		road_secondary: "#FF00C8",
		road_tertiary: "#9B7CFF",
		road_residential: "#6EE7B7",
		road_default: "#00E5FF"
	},
	mint_fizz: {
		name: "Mint Fizz",
		description: "Fresh minty pastels for a calm, modern map",
		bg: "#F4FFFB",
		text: "#09332A",
		water: "#DFFCF4",
		parks: "#CCFBF1",
		road_motorway: "#34D399",
		road_primary: "#6EE7B7",
		road_secondary: "#4ADE80",
		road_tertiary: "#86EFAC",
		road_residential: "#D1FAE5",
		road_default: "#4ADE80"
	},
	monochrome_pro: {
		name: "Monochrome Pro",
		description: "Balanced greyscale for professional architectural maps",
		bg: "#FFFFFF",
		text: "#18181B",
		water: "#F4F4F5",
		parks: "#E4E4E7",
		road_motorway: "#18181B",
		road_primary: "#3F3F46",
		road_secondary: "#52525B",
		road_tertiary: "#71717A",
		road_residential: "#A1A1AA",
		road_default: "#52525B"
	},
	cyber_noir: {
		name: "Cyber Noir",
		description: "Dark background with vibrant neon stripe palette",
		bg: "#0B0B16",
		text: "#00E5E5",
		gradient_color: "#0B0B16",
		water: "#071020",
		parks: "#111122",
		road_motorway: "#FF2AE6",
		road_primary: "#00E5FF",
		road_secondary: "#00BEBE",
		road_tertiary: "#008F95",
		road_residential: "#005E66",
		road_default: "#008F95"
	},
	paper_heritage: {
		name: "Paper Heritage",
		description: "Soft sepia tones and inked roads for vintage prints",
		bg: "#FBF6EE",
		text: "#3B2F2F",
		water: "#EAE2D6",
		parks: "#F5E9D4",
		road_motorway: "#7A4B2D",
		road_primary: "#9A6B3A",
		road_secondary: "#B77A3A",
		road_tertiary: "#D29A55",
		road_residential: "#F1E2CF",
		road_default: "#B77A3A"
	},
	rustic_clay: {
		name: "Rustic Clay",
		description: "Earthy reds and warm oranges - sun-baked urban style",
		bg: "#FFF7ED",
		text: "#7C2D12",
		water: "#FFEDD5",
		parks: "#FED7AA",
		road_motorway: "#9A3412",
		road_primary: "#C2410C",
		road_secondary: "#EA580C",
		road_tertiary: "#F97316",
		road_residential: "#FB923C",
		road_default: "#EA580C"
	},
	sunset_blush: {
		name: "Sunset Blush",
		description: "Warm pinks and corals mimicking a coastal sunset",
		bg: "#FFF5F7",
		text: "#6B1226",
		water: "#FFE4E6",
		parks: "#FFD6E0",
		road_motorway: "#FF7A59",
		road_primary: "#FF6B6B",
		road_secondary: "#FF8FA3",
		road_tertiary: "#FFB4C6",
		road_residential: "#FFECEC",
		road_default: "#FF6B6B"
	},
	volcanic_ash: {
		name: "Volcanic Ash",
		description: "Deep charcoal and glowing embers - high drama style",
		bg: "#1C1917",
		text: "#FAFAF9",
		water: "#0C0A09",
		parks: "#292524",
		road_motorway: "#EF4444",
		road_primary: "#F87171",
		road_secondary: "#B91C1C",
		road_tertiary: "#7F1D1D",
		road_residential: "#450A0A",
		road_default: "#B91C1C"
	}
};
